// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/region": {
            "get": {
                "description": "모든 지역 정보를 반환합니다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "region"
                ],
                "summary": "모든 지역 조회",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Region"
                            }
                        }
                    }
                }
            }
        },
        "/api/region/search": {
            "get": {
                "description": "쿼리 파라미터로 지역을 검색합니다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "region"
                ],
                "summary": "지역 검색",
                "parameters": [
                    {
                        "type": "string",
                        "description": "지역 ID",
                        "name": "region_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "지역명",
                        "name": "region_name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "X 좌표",
                        "name": "coord_x",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Y 좌표",
                        "name": "coord_y",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "최대 용량",
                        "name": "max_capacity",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "현재 용량",
                        "name": "current_capacity",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "포화 여부",
                        "name": "is_full",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "포화 시각(RFC3339)",
                        "name": "saturated_at",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Region"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/region/{id}": {
            "get": {
                "description": "지역 ID로 지역 정보를 조회합니다.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "region"
                ],
                "summary": "지역 단건 조회",
                "parameters": [
                    {
                        "type": "string",
                        "description": "지역 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Region"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Region": {
            "type": "object",
            "properties": {
                "coord_x": {
                    "type": "integer"
                },
                "coord_y": {
                    "type": "integer"
                },
                "current_capacity": {
                    "type": "integer"
                },
                "is_full": {
                    "type": "boolean"
                },
                "max_capacity": {
                    "type": "integer"
                },
                "region_id": {
                    "type": "string"
                },
                "region_name": {
                    "type": "string"
                },
                "saturated_at": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Go API Server",
	Description:      "패키지 운송 시스템 API 문서입니다.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
